### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by MarekPikula** [Dattel/homeassistant-influxdb2#2]
Hi, I just tried to install the add-on on my HAS instance and got the following error:

> The command '/bin/bash -o pipefail -c apt-get update && ARCH="${BUILD_ARCH}" && if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi && INFLUXDB="2.7.1" && curl -J -L -o /tmp/influxdb2.deb "https://dl.influxdata.com/influxdb/releases/influxdb2-${INFLUXDB}-${ARCH}.deb" && curl -J -L -o /tmp/influxdb-cli.deb "https://dl.influxdata.com/influxdb/releases/influxdb2-client-${INFLUXDB}-${ARCH}.deb" && dpkg --install /tmp/influxdb2.deb && dpkg --install /tmp/influxdb-cli.deb && rm -fr /tmp/* /var/{cache,log}/* /var/lib/apt/lists/* && mkdir -p /data/influxdb2/engine' returned a non-zero code: 6

I'm running:

> Home Assistant 2023.5.2
> Supervisor 2023.04.1
> Operating System 10.1
> Frontend 20230503.3 - latest

on an x86_64 VM under qemu.

The curious part is that I tested it on an RPi4 and a very similar VM on another machine, and it was installed successfully.

I can see that it is an error in the Docker build. I think that it might be a good idea, either way, to build the image in CI and use it in the addon config instead of building the image directly on the host. Here is a snippet from one of my private projects, which uses GH Actions to do just this:

```yaml
name: Build Docker image
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}:${{ steps.extract_branch.outputs.branch }}
          context: .
          cache-from: type=registry,ref=${{ secrets.REGISTRY_URL }}:buildcache
          cache-to: type=registry,ref=${{ secrets.REGISTRY_URL }}:buildcache,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```

You can set the secrets according to the GHCR guide: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
